# Generated by Django 2.1.3 on 2018-11-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofileinfo',
            table='UserProfileInfo',
        ),
    ]
