# Generated by Django 2.1.3 on 2018-11-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='new_user',
            name='subinstitute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
