# Generated by Django 2.1.2 on 2018-11-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181115_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='institutes',
            name='id',
        ),
        migrations.AlterField(
            model_name='campus',
            name='id_campus',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='college',
            name='telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='id_institute',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modify_place',
            name='telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modify_user',
            name='personal_telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='personal_telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subinstitutes',
            name='telephone',
            field=models.CharField(max_length=200),
        ),
    ]
