# Generated by Django 2.1.2 on 2018-11-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20181121_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Campus'),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modify_place',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modify_place',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modify_user',
            name='academic_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modify_user',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modify_user',
            name='personal_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='academic_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='personal_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='academic_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='database.Groups'),
        ),
        migrations.AlterField(
            model_name='people',
            name='personal_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='subinstitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Subinstitutes'),
        ),
        migrations.AlterField(
            model_name='public',
            name='academic_level',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='degree',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='id_subinstitute',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='personal_telephone',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register_place',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='register_place',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subinstitutes',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subinstitutes',
            name='id_reference_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Subinstitutes'),
        ),
        migrations.AlterField(
            model_name='subinstitutes',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='upload_document',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload_document',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
