# Generated by Django 2.1.2 on 2018-11-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20181121_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='papers',
            field=models.ManyToManyField(to='database.Papers'),
        ),
        migrations.AlterField(
            model_name='people',
            name='groups',
            field=models.ManyToManyField(to='database.Groups'),
        ),
    ]
